// Code generated by getprotogen/generate.go. DO NOT EDIT.

package main

import (
	"google.golang.org/protobuf/reflect/protoreflect"
)

func forEachFile(f func(string, protoreflect.FileDescriptor)) {
}
