// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporal/server/api/enums/v1/flow_control.proto

package enums

import (
	reflect "reflect"
	"strconv"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LimiterType int32

const (
	LIMITER_TYPE_UNSPECIFIED LimiterType = 0
	LIMITER_TYPE_CONCURRENCY LimiterType = 1
)

// Enum value maps for LimiterType.
var (
	LimiterType_name = map[int32]string{
		0: "LIMITER_TYPE_UNSPECIFIED",
		1: "LIMITER_TYPE_CONCURRENCY",
	}
	LimiterType_value = map[string]int32{
		"LIMITER_TYPE_UNSPECIFIED": 0,
		"LIMITER_TYPE_CONCURRENCY": 1,
	}
)

func (x LimiterType) Enum() *LimiterType {
	p := new(LimiterType)
	*p = x
	return p
}

func (x LimiterType) String() string {
	switch x {
	case LIMITER_TYPE_UNSPECIFIED:
		return "Unspecified"
	case LIMITER_TYPE_CONCURRENCY:
		return "Concurrency"
	default:
		return strconv.Itoa(int(x))
	}

}

func (LimiterType) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_server_api_enums_v1_flow_control_proto_enumTypes[0].Descriptor()
}

func (LimiterType) Type() protoreflect.EnumType {
	return &file_temporal_server_api_enums_v1_flow_control_proto_enumTypes[0]
}

func (x LimiterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LimiterType.Descriptor instead.
func (LimiterType) EnumDescriptor() ([]byte, []int) {
	return file_temporal_server_api_enums_v1_flow_control_proto_rawDescGZIP(), []int{0}
}

var File_temporal_server_api_enums_v1_flow_control_proto protoreflect.FileDescriptor

const file_temporal_server_api_enums_v1_flow_control_proto_rawDesc = "" +
	"\n" +
	"/temporal/server/api/enums/v1/flow_control.proto\x12\x1ctemporal.server.api.enums.v1*I\n" +
	"\vLimiterType\x12\x1c\n" +
	"\x18LIMITER_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18LIMITER_TYPE_CONCURRENCY\x10\x01B*Z(go.temporal.io/server/api/enums/v1;enumsb\x06proto3"

var (
	file_temporal_server_api_enums_v1_flow_control_proto_rawDescOnce sync.Once
	file_temporal_server_api_enums_v1_flow_control_proto_rawDescData []byte
)

func file_temporal_server_api_enums_v1_flow_control_proto_rawDescGZIP() []byte {
	file_temporal_server_api_enums_v1_flow_control_proto_rawDescOnce.Do(func() {
		file_temporal_server_api_enums_v1_flow_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_server_api_enums_v1_flow_control_proto_rawDesc), len(file_temporal_server_api_enums_v1_flow_control_proto_rawDesc)))
	})
	return file_temporal_server_api_enums_v1_flow_control_proto_rawDescData
}

var file_temporal_server_api_enums_v1_flow_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_temporal_server_api_enums_v1_flow_control_proto_goTypes = []any{
	(LimiterType)(0), // 0: temporal.server.api.enums.v1.LimiterType
}
var file_temporal_server_api_enums_v1_flow_control_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_temporal_server_api_enums_v1_flow_control_proto_init() }
func file_temporal_server_api_enums_v1_flow_control_proto_init() {
	if File_temporal_server_api_enums_v1_flow_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_server_api_enums_v1_flow_control_proto_rawDesc), len(file_temporal_server_api_enums_v1_flow_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_server_api_enums_v1_flow_control_proto_goTypes,
		DependencyIndexes: file_temporal_server_api_enums_v1_flow_control_proto_depIdxs,
		EnumInfos:         file_temporal_server_api_enums_v1_flow_control_proto_enumTypes,
	}.Build()
	File_temporal_server_api_enums_v1_flow_control_proto = out.File
	file_temporal_server_api_enums_v1_flow_control_proto_goTypes = nil
	file_temporal_server_api_enums_v1_flow_control_proto_depIdxs = nil
}
