// Code generated by protoc-gen-go-helpers. DO NOT EDIT.
package enums

import (
	"fmt"
)

var (
	LimiterType_shorthandValue = map[string]int32{
		"Unspecified": 0,
		"Concurrency": 1,
	}
)

// LimiterTypeFromString parses a LimiterType value from  either the protojson
// canonical SCREAMING_CASE enum or the traditional temporal PascalCase enum to LimiterType
func LimiterTypeFromString(s string) (LimiterType, error) {
	if v, ok := LimiterType_value[s]; ok {
		return LimiterType(v), nil
	} else if v, ok := LimiterType_shorthandValue[s]; ok {
		return LimiterType(v), nil
	}
	return LimiterType(0), fmt.Errorf("%s is not a valid LimiterType", s)
}
