syntax = "proto3";

package temporal.server.chasm.lib.flowcontrol.proto.v1;

import "google/protobuf/timestamp.proto";
import "temporal/api/taskqueue/v1/message.proto";
import "temporal/server/api/common/v1/api_category.proto";
import "temporal/server/api/routing/v1/extension.proto";

option go_package = "go.temporal.io/server/chasm/lib/flowcontrol/gen/fcpb;fcpb";

message ConcurrencyState {
  // Limit of concurrent slots; maximum length of slots.
  int32 limit = 1;
  // Slots reserved or committed. Entries should be unique by task_uuid.
  repeated ConcurrencySlot slots = 2;
  // Generation is used to ensure Wait is monotonic. See comment in Wait for details.
  int64 generation = 3;
}

message ConcurrencySlot {
  // Task UUID of task.
  string task_uuid = 1;
  // Whether slot is committed or only reserved. Reserved slots must have an expiry time.
  // Committed slots don't expire, they must be Released.
  bool committed = 2;
  // Expiry time for reserved slot.
  google.protobuf.Timestamp expires = 3;
}

message ConcurrencyReserveRequest {
  string namespace_id = 1;
  string key = 2;
  string task_uuid = 3;

  // For whole-task-queue limits, the initial limit and updates to the limit come through task
  // queue config, so we need to pass them to the chasm object. We just do it on every Reserve.
  temporal.api.taskqueue.v1.ConcurrencyLimit limit_update = 4;
}

message ConcurrencyReserveResponse {
  // Generation of limiter state.
  int64 generation = 1;
  // Number of slots reserved, 0 or 1. On insufficient slots, Reserve returns zero
  // slots_reserved, not an error. This makes it easy to also include the generation.
  int32 slots_reserved = 2;
}

message ConcurrencyCancelReservationRequest {
  string namespace_id = 1;
  string key = 2;
  string task_uuid = 3;
}

message ConcurrencyCancelReservationResponse {
}

message ConcurrencyCommitRequest {
  string namespace_id = 1;
  string key = 2;
  string task_uuid = 3;
}

message ConcurrencyCommitResponse {
}

message ConcurrencyReleaseRequest {
  string namespace_id = 1;
  string key = 2;
  string task_uuid = 3;
}

message ConcurrencyReleaseResponse {
}

message ConcurrencyWaitRequest {
  string namespace_id = 1;
  string key = 2;
  // If generation is out of date, returns immediately with new generation.
  int64 generation = 3;
  // FIXME: add something to identify waiters so we can do selective wakeup
}

message ConcurrencyWaitResponse {
  // Generation of limiter state.
  int64 generation = 1;
  // Number of slots that the client should consider available. This may be less than the
  // number of free slots, if the limiter wants to divide available slots among multiple
  // waiters.
  int32 wake_count = 2;
}

service ConcurrencyService {
  // Reserve reserves a slot for a limited time. Succeeds if the slot is newly reserved or
  // already reserved _or already committed_ for the task, i.e. idempotent. May not be durable:
  // a successful Reserve followed by a Commit may not succeed even within the timeout. Callers
  // must handle that situation correctly.
  rpc Reserve(ConcurrencyReserveRequest) returns (ConcurrencyReserveResponse) {
    option (temporal.server.api.routing.v1.routing).business_id = "key";
    option (temporal.server.api.common.v1.api_category).category = API_CATEGORY_STANDARD;
  };
  // CancelReservation cancels a reservation early. Note that committed slots cannot be
  // canceled, they must be Released. Idempotent. May not be durable.
  rpc CancelReservation(ConcurrencyCancelReservationRequest) returns (ConcurrencyCancelReservationResponse) {
    option (temporal.server.api.routing.v1.routing).business_id = "key";
    option (temporal.server.api.common.v1.api_category).category = API_CATEGORY_STANDARD;
  };
  // Commit promotes a reservation to a committed slot. Succeeds if the reservation was
  // promoted, or was already committed, i.e. idempotent. Durable.
  rpc Commit(ConcurrencyCommitRequest) returns (ConcurrencyCommitResponse) {
    option (temporal.server.api.routing.v1.routing).business_id = "key";
    option (temporal.server.api.common.v1.api_category).category = API_CATEGORY_STANDARD;
  };
  // Release frees a comitted slot. Succeeds if the committed slot was released or if there was
  // no committed slot, i.e. idempotent. Durable.
  rpc Release(ConcurrencyReleaseRequest) returns (ConcurrencyReleaseResponse) {
    option (temporal.server.api.routing.v1.routing).business_id = "key";
    option (temporal.server.api.common.v1.api_category).category = API_CATEGORY_STANDARD;
  };
  // Wait is a long-poll RPC that returns when at least one slot is free, or the caller's
  // generation is too old.
  rpc Wait(ConcurrencyWaitRequest) returns (ConcurrencyWaitResponse) {
    option (temporal.server.api.routing.v1.routing).business_id = "key";
    option (temporal.server.api.common.v1.api_category).category = API_CATEGORY_LONG_POLL;
  };
}
