// The MIT License
//
// Copyright (c) 2020 Temporal Technologies Inc.  All rights reserved.
//
// Copyright (c) 2020 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package scheduler

import (
	"context"
	"errors"
	"time"

	enumspb "go.temporal.io/api/enums/v1"
	schedpb "go.temporal.io/api/schedule/v1"
	"go.temporal.io/api/workflowservice/v1"
	sdklog "go.temporal.io/sdk/log"
	"go.temporal.io/sdk/temporal"
	"go.temporal.io/sdk/workflow"

	"go.temporal.io/server/common/log"
	"go.temporal.io/server/common/metrics"
	"go.temporal.io/server/common/primitives/timestamp"
)

const (
	WorkflowName = "temporal-sys-scheduler-workflow"

	// The number of future action times to include in Describe.
	futureActionCount = 10
	// The number of recent actual action results to include in Describe.
	recentActionCount = 10

	iterationsBeforeContinueAsNew = 500
)

type (
	activities struct {
		metricsClient metrics.Client
		logger        log.Logger
	}

	// FIXME: should this be a proto?
	internalState struct {
		LastProcessedTime time.Time
	}

	scheduler struct {
		ctx    workflow.Context
		id     string
		a      *activities
		logger sdklog.Logger
		schedpb.Schedule
		internalState
		cspec *compiledSpec
	}
)

func SchedulerWorkflow(ctx workflow.Context, id string, s *schedpb.Schedule, internal *internalState) error {
	scheduler := &scheduler{
		ctx:      ctx,
		id:       id,
		a:        nil,
		logger:   sdklog.With(workflow.GetLogger(ctx), "schedule-id", id),
		Schedule: *s,
	}
	if internal != nil {
		scheduler.internalState = *internal
	}
	return scheduler.run()
}

func (s *scheduler) run() error {
	s.logger.Info("Schedule started")

	s.ensureFields()
	s.compile()

	if err := workflow.SetQueryHandler(s.ctx, "describe", s.describe); err != nil {
		return err
	}

	if s.LastProcessedTime.IsZero() {
		s.logger.Debug("Initializing processed time")
		s.LastProcessedTime = s.now()
		s.Info.CreateTime = timestamp.TimePtr(s.LastProcessedTime)
	}

	s.processRequest()

	for iters := iterationsBeforeContinueAsNew; iters >= 0; iters-- {
		t2 := s.now()
		if t2.Before(s.LastProcessedTime) {
			// Time went backwards. If this is a large jump, we may want to
			// handle it differently, but for now, do nothing until we get back
			// up to the last processed time.
			s.logger.Warn("Time went backwards", "from", s.LastProcessedTime, "to", t2)
			t2 = s.LastProcessedTime
		}
		nextSleep, hasNext := s.processTimeRange(
			s.LastProcessedTime, t2,
			s.Policies.OverlapPolicy,
			false,
		)
		s.LastProcessedTime = t2
		s.sleep(nextSleep, hasNext)
	}

	s.logger.Info("Schedule doing continue-as-new")
	return workflow.NewContinueAsNewError(s.ctx, WorkflowName, s.id, &s.Schedule, &s.internalState)
}

func (s *scheduler) ensureFields() {
	if s.Spec == nil {
		s.Spec = &schedpb.ScheduleSpec{}
	}
	if s.Action == nil {
		s.Action = &schedpb.ScheduleAction{}
	}
	if s.Policies == nil {
		s.Policies = &schedpb.SchedulePolicies{}
	}
	if s.State == nil {
		s.State = &schedpb.ScheduleState{}
	}
	if s.Info == nil {
		s.Info = &schedpb.ScheduleInfo{}
	}
}

func (s *scheduler) compile() {
	cspec, err := newCompiledSpec(s.Spec)
	if err != nil {
		s.logger.Error("Invalid schedule", "error", err)
		s.Info.InvalidScheduleError = err.Error()
		s.cspec = nil
	} else {
		s.Info.InvalidScheduleError = ""
		s.cspec = cspec
	}
}

func (s *scheduler) now() time.Time {
	// TODO: potential issues:
	// 1. the go sdk enforces monotonic time. but we might want to do something
	// different if the real time (on the server worker) goes backwards, e.g.
	// due to a large time adjustment. so maybe we could get time.Now in a side
	// effect? I think that'll increase the history size though.
	// 2. how accurate is this? it's the time of the workflowtaskstarted event,
	// which is generated by the history service. actually it's a transient
	// event: it's not written to history until the wft is completed (I think),
	// and it's pasted into the history that the worker sees by the frontend.
	// as far as I can tell, this value is taken from wall time by history at
	// the time when matching tells it that the wft is about to be returned to a
	// worker. the delay from history->matching->frontend->worker is hopefully
	// well under a second, which is all we care about, so it's probably close
	// enough.
	return workflow.Now(s.ctx)
}

func (s *scheduler) processRequest() {
	if s.Request == nil {
		return
	}

	if s.Request.TriggerImmediately {
		now := s.now()
		s.action(now, now, s.Policies.OverlapPolicy)
	}

	for _, bfr := range s.Request.BackfillRequest {
		s.processTimeRange(
			timestamp.TimeValue(bfr.GetFromTime()),
			timestamp.TimeValue(bfr.GetToTime()),
			bfr.GetOverlapPolicy(),
			true,
		)
	}

	s.Request = nil
}

func (s *scheduler) processTimeRange(
	t1, t2 time.Time,
	overlapPolicy enumspb.ScheduleOverlapPolicy,
	doingBackfill bool,
) (nextSleep time.Duration, hasNext bool) {
	if s.cspec == nil {
		return 0, false
	}

	if overlapPolicy == enumspb.SCHEDULE_OVERLAP_POLICY_UNSPECIFIED {
		overlapPolicy = s.Policies.OverlapPolicy
	}
	catchupWindow := s.getCatchupWindow()

	for {
		// FIXME: consider wrapping in side effect so it can be changed easily?
		nominalTime, nextTime, hasNext := s.cspec.getNextTime(s.State, t1, doingBackfill)
		if !hasNext {
			return 0, false
		} else if nextTime.After(t2) {
			return nextTime.Sub(t2), true
		}
		// FIXME: should this be nextTime or nominalTime? what if someone sets jitter above catchup window?
		if !doingBackfill && t2.Sub(nextTime) > catchupWindow {
			s.logger.Warn("Schedule missed catchup window", "now", t2, "time", nextTime)
			s.Info.MissedCatchupWindow++
			continue
		}
		s.action(nominalTime, nextTime, overlapPolicy)
		// FIXME: if pause-after-failure, set up goroutine to watch this one
		t1 = nextTime
	}
}

func (s *scheduler) sleep(nextSleep time.Duration, hasNext bool) {
	sel := workflow.NewSelector(s.ctx)

	sch := workflow.GetSignalChannel(s.ctx, "update")
	sel.AddReceive(sch, s.update)

	if hasNext {
		tmr := workflow.NewTimer(s.ctx, nextSleep)
		sel.AddFuture(tmr, func(_ workflow.Future) {})
	}

	sel.Select(s.ctx)
}

func (s *scheduler) update(ch workflow.ReceiveChannel, _ bool) {
	var newSchedule schedpb.Schedule
	ch.Receive(s.ctx, &newSchedule)

	s.logger.Info("Schedule update", "new-schedule", newSchedule.String())

	// FIXME: any special transition handling here?

	s.Schedule.Spec = newSchedule.Spec
	s.Schedule.Action = newSchedule.Action
	s.Schedule.Policies = newSchedule.Policies
	s.Schedule.State = newSchedule.State
	s.Schedule.Request = newSchedule.Request
	// don't touch Info

	s.ensureFields()
	s.compile()

	s.Info.UpdateTime = timestamp.TimePtr(s.now())

	s.processRequest()
}

func (s *scheduler) describe() (*schedpb.Schedule, error) {
	// update future actions
	if s.cspec != nil {
		s.Info.FutureActions = make([]*time.Time, 0, futureActionCount)
		t1 := s.now()
		for len(s.Info.FutureActions) < cap(s.Info.FutureActions) {
			_, t1, has := s.cspec.getNextTime(s.State, t1, false)
			if !has {
				break
			}
			s.Info.FutureActions = append(s.Info.FutureActions, timestamp.TimePtr(t1))
		}
	} else {
		s.Info.FutureActions = nil
	}

	return &s.Schedule, nil
}

func (s *scheduler) getCatchupWindow() time.Duration {
	cw := s.Policies.CatchupWindow
	if cw == nil {
		return 60 * time.Second
	} else if *cw < 10*time.Second {
		return 10 * time.Second
	} else {
		return *cw
	}
}

func (s *scheduler) action(nominalTime, actualTime time.Time, overlapPolicy enumspb.ScheduleOverlapPolicy) {
	if overlapPolicy == enumspb.SCHEDULE_OVERLAP_POLICY_UNSPECIFIED {
		overlapPolicy = enumspb.SCHEDULE_OVERLAP_POLICY_SKIP
	}
	appendTime := overlapPolicy == enumspb.SCHEDULE_OVERLAP_POLICY_ALLOW_ALL

	if s.Action.GetStartWorkflow() != nil {
		// Validation
		// namespace: already validated at creation time
		// identity: set by SDK? FIXME
		// request_id: FIXME
		// workflow_id_reuse_policy: FIXME must be omitted or set to WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE.
		// cron_schedule: FIXME

		ctx1 := workflow.WithActivityOptions(s.ctx, workflow.ActivityOptions{
			RetryPolicy: &temporal.RetryPolicy{
				InitialInterval: 1 * time.Second,
			},
		})
		var result error
		err := workflow.ExecuteActivity(ctx1, s.a.StartWorkflow, req).Get(s.ctx, &result)
		// FIXME: do something with err, result
	}

	s.Info.ActionCount++
	// FIXME: append action result
	// s.Info.RecentActions = append(s.Info.RecentActions, timestamp.TimePtr(actualTime))
	extra := len(s.Info.RecentActions) - 10
	if extra > 0 {
		s.Info.RecentActions = s.Info.RecentActions[extra:]
	}

	if s.State.LimitedActions && s.State.RemainingActions > 0 {
		s.State.RemainingActions--
	}
}

func (a *activities) StartWorkflow(ctx context.Context, req *workflowservice.StartWorkflowExecutionRequest) error {
	// send req directly to frontend, or to history?
	return errors.New("FIXME")
}
